apiVersion: v1
kind: Service
metadata:
  name: devtool-ui
  labels:
    app: vbpe
    module: devtool-ui
  annotations:
    ingress.kubernetes.io/service-upstream: "true"
spec:
  ports:
    - name: devtool-ui-port
      protocol: TCP
      targetPort: 80
      port: 80
      nodePort: 4500
  selector:
    app: vbpe
  type: NodePort

